name: Security CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: apps/api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: npm audit
        run: npm audit --omit=dev --audit-level=high


  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  terraform-security:
    name: Terraform Security Scan (Learning Mode)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform
          framework: terraform
          skip_check: CKV_AWS_2,CKV_AWS_103,CKV2_AWS_20,CKV_AWS_378,CKV_AWS_91,CKV2_AWS_28,CKV_AWS_333,CKV_AWS_130,CKV2_AWS_5,CKV2_AWS_57,CKV2_AWS_11,CKV_AWS_260
          # Keep findings visible but non-blocking for low-cost learning environments.
          soft_fail: true
